apiVersion: v1
kind: Service
metadata:
  name: {{ default "onos-service" .Values.service.name }}
  namespace: {{ default "transport-network" .Values.namespace }}
spec:
  selector:
    app: {{ include "onos.selectorName" . }}
  type: {{ default "NodePort" .Values.service.type }}
  ports:
  - name: rest
    port: {{ default 8181 .Values.service.ports.rest.port }}
    targetPort: {{ default 8181 .Values.service.ports.rest.port }}
    {{- if eq (default "NodePort" .Values.service.type) "NodePort" }}
    nodePort: {{ default 30181 .Values.service.ports.rest.nodePort }}
    {{- end }}
  - name: karaf
    port: {{ default 8101 .Values.service.ports.karaf.port }}
    targetPort: {{ default 8101 .Values.service.ports.karaf.port }}
    {{- if eq (default "NodePort" .Values.service.type) "NodePort" }}
    nodePort: {{ default 30101 .Values.service.ports.karaf.nodePort }}
    {{- end }}
  - name: debug
    port: {{ default 5005 .Values.service.ports.debug.port }}
    targetPort: {{ default 5005 .Values.service.ports.debug.port }}
    {{- if eq (default "NodePort" .Values.service.type) "NodePort" }}
    nodePort: {{ default 30505 .Values.service.ports.debug.nodePort }}
    {{- end }}
  - name: netconf1
    port: {{ default 830 .Values.service.ports.netconf1.port }}
    targetPort: {{ default 830 .Values.service.ports.netconf1.port }}
    {{- if eq (default "NodePort" .Values.service.type) "NodePort" }}
    nodePort: {{ default 30083 .Values.service.ports.netconf1.nodePort }}
    {{- end }}
  - name: openflow
    port: {{ default 6653 .Values.service.ports.openflow.port }}
    targetPort: {{ default 6653 .Values.service.ports.openflow.port }}
    {{- if eq (default "NodePort" .Values.service.type) "NodePort" }}
    nodePort: {{ default 31653 .Values.service.ports.openflow.nodePort }}
    {{- end }}
