apiVersion: v1
kind: Namespace
metadata:
  name: transport-network
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring


