apiVersion: batch/v1
kind: Job
metadata:
  name: onos-plugins
  namespace: transport-network
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: onos-plugins
        image: curlimages/curl
        command: [ "sh", "-c" ]
        args:
          - |
            sleep 30 &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.openflow-message/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.workflow.ofoverlay/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.openflow/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.ofagent/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.fwd/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://onos-service.transport-network.svc.cluster.local:8181/onos/v1/applications/org.onosproject.proxyarp/active' --user 'onos:rocks'