# telegraf-daemonset.yaml (Versão Final e Corrigida)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: transport-network
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: telegraf
        image: telegraf:1.36.1
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-token
              key: token
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: telegraf-config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: telegraf-config-volume
        configMap:
          name: telegraf-config