# telegraf-rbac.yaml (Versão Final e Corrigida)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  namespace: transport-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/spec
  - nodes/stats
  - nodes/metrics
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - "/metrics"
  - "/metrics/cadvisor"
  - "/stats/*"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: transport-network