# telegraf-configmap.yaml (CORRIGIDO)
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: transport-network
data:
  telegraf.conf: |-
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = "$HOSTNAME"
      omit_hostname = false

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb-influxdb2.transport-network.svc.cluster.local:8086"]
      token = "$INFLUX_TOKEN"
      organization = "lasse"
      bucket = "kubernetes"
      
    [[inputs.kubernetes]]
      insecure_skip_verify = true 

    [[inputs.kube_inventory]]
      resource_include = [
        "nodes", "services", "endpoints", "pods", "namespaces",
        "deployments", "replicasets", "statefulsets", "daemonsets"
      ]