{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-plugins" (include "onos.fullname" .) }}
  namespace: {{ default "transport-network" .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: onos-plugins
        image: {{ default "curlimages/curl" .Values.job.image }}
        command: ["sh", "-c"]
        args:
          - |
            sleep {{ default 30 .Values.job.sleepSeconds }} &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.openflow-message/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.workflow.ofoverlay/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.openflow/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.ofagent/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.fwd/active' --user 'onos:rocks' &&
            curl -X POST --header 'Accept: application/json' 'http://{{ default "onos-service" .Values.service.name }}.{{ default "transport-network" .Values.namespace }}.svc.cluster.local:{{ default 8181 .Values.service.ports.rest.port }}/onos/v1/applications/org.onosproject.proxyarp/active' --user 'onos:rocks'
{{- end }}
