# telegraf-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.fullname" . }}-config
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
  telegraf.conf: |-
{{ .Values.rawConfig | nindent 4 }}